Already up-to-date.
make -C build-tools all
make[1]: Entering directory '/home/zededa-ci/src/zenbuild/build-tools'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/zededa-ci/src/zenbuild/build-tools'
Already up-to-date.
Building and pushing "zededa/ztools:df7aa73bcb5a5934f8ea5b7b67ca6dce62a85d0a"
df7aa73bcb5a5934f8ea5b7b67ca6dce62a85d0a: Pulling from zededa/ztools
no matching manifest for linux/arm64 in the manifest list entries
No image pulled, continuing with build
Sending build context to Docker daemon  15.55MB
Step 1/33 : FROM golang:1.9.1-alpine AS build
 ---> cc52d0ad4cce
Step 2/33 : RUN apk update
 ---> Using cache
 ---> edc6a248f562
Step 3/33 : RUN apk add --no-cache git gcc linux-headers libc-dev util-linux
 ---> Using cache
 ---> adf91ff4a5f2
Step 4/33 : ADD ./ /go/src/github.com/zededa/go-provision/
 ---> Using cache
 ---> d9e5b703e469
Step 5/33 : ADD etc /config
 ---> Using cache
 ---> baf9c5ac6180
Step 6/33 : ADD scripts/device-steps.sh scripts/find-uplink.sh scripts/generate-device.sh scripts/generate-self-signed.sh scripts/handlezedserverconfig.sh /opt/zededa/bin/
 ---> Using cache
 ---> 14191ba79374
Step 7/33 : ADD examples /opt/zededa/examples
 ---> Using cache
 ---> d2c5eeba06d0
Step 8/33 : ADD AssignableAdapters /var/tmp/zededa/AssignableAdapters
 ---> Using cache
 ---> cec40fda5b6d
Step 9/33 : ADD DeviceNetworkConfig /var/tmp/zededa/DeviceNetworkConfig
 ---> Using cache
 ---> 1a8bcd9bccba
Step 10/33 : ADD lisp.config.base /var/tmp/zededa/lisp.config.base
 ---> Using cache
 ---> cc291b577805
Step 11/33 : RUN (cd ./src/github.com/zededa/go-provision/; scripts/getversion.sh >/opt/zededa/bin/versioninfo)
 ---> Using cache
 ---> ddfe32011b88
Step 12/33 : RUN echo Building: `cat /opt/zededa/bin/versioninfo`
 ---> Using cache
 ---> c43a2a3820d8
Step 13/33 : RUN go install github.com/zededa/go-provision/cmd/...
 ---> Running in 736bc0fcfea5
[91mcontainer_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 0 caused \\\"error running hook: exit status 2, stdout: , stderr: runtime/cgo: pthread_create failed: Resource temporarily unavailable\\\\nSIGABRT: abort\\\\nPC=0x1347ec8 m=3 sigcode=18446744073709551610\\\\n\\\\ngoroutine 0 [idle]:\\\\n\\\\ngoroutine 1 [IO wait]:\\\\nnet.runtime_pollWait(0xffffa2a7bf70, 0x72, 0x5)\\\\n\\\\t/usr/src/go/src/runtime/netpoll.go:164 +0x3c\\\\nnet.(*pollDesc).wait(0x442043ce68, 0x72, 0xffffffffffffffff, 0x231f880)\\\\n\\\\t/usr/src/go/src/net/fd_poll_runtime.go:75 +0x2c\\\\nnet.(*pollDesc).waitRead(0x442043ce68, 0x4420415400, 0x400)\\\\n\\\\t/usr/src/go/src/net/fd_poll_runtime.go:80 +0x28\\\\nnet.(*netFD).Read(0x442043ce00, 0x4420415400, 0x400, 0x400, 0x0, 0x231f880, 0x2311978)\\\\n\\\\t/usr/src/go/src/net/fd_unix.go:250 +0x148\\\\nnet.(*conn).Read(0x442000e790, 0x4420415400, 0x400, 0x400, 0x0, 0x0, 0x0)\\\\n\\\\t/usr/src/go/src/net/net.go:181 +0x50\\\\ngithub.com/docker/docker/vendor/github.com/docker/libnetwork.processReturn(0xffffa2a7c228, 0x442000e790, 0x442000e790, 0xffffa2a7c228)\\\\n\\\\t/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox_externalkey_unix.go:94 +0x64\\\\ngithub.com/docker/docker/vendor/github.com/docker/libnetwork.SetExternalKey(0xfffff7907f27, 0x40, 0xfffff7907ee6, 0x40, 0x442042eee0, 0x12, 0x0, 0x0)\\\\n\\\\t/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox_externalkey_unix.go:72 +0x1a4\\\\ngithub.com/docker/docker/vendor/github.com/docker/libnetwork.processSetKeyReexec()\\\\n\\\\t/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox_externalkey_unix.go:54 +0x1dc\\\\ngithub.com/docker/docker/pkg/reexec.Init(0x0)\\\\n\\\\t/go/src/github.com/docker/docker/pkg/reexec/reexec.go:26 +0x7c\\\\nmain.main()\\\\n\\\\t/go/src/github.com/docker/docker/cmd/dockerd/docker.go:88 +0x18\\\\n\\\\ngoroutine 17 [syscall, locked to thread]:\\\\nruntime.goexit()\\\\n\\\\t/usr/src/go/src/runtime/asm_arm64.s:981 +0x4\\\\n\\\\ngoroutine 6 [syscall]:\\\\nos/signal.signal_recv(0x0)\\\\n\\\\t/usr/src/go/src/runtime/sigqueue.go:116 +0xd8\\\\nos/signal.loop()\\\\n\\\\t/usr/src/go/src/os/signal/signal_unix.go:22 +0x18\\\\ncreated by os/signal.init.1\\\\n\\\\t/usr/src/go/src/os/signal/signal_unix.go:28 +0x30\\\\n\\\\nr0      0x0\\\\nr1      0x4fe0\\\\nr2      0x6\\\\nr3      0xffffa42aa090\\\\nr4      0x4fd5\\\\nr5      0xffffa42aa780\\\\nr6      0x0\\\\nr7      0x0\\\\nr8      0x83\\\\nr9      0xffffff80ffffffc8\\\\nr10     0x73\\\\nr11     0xffffa42a6bb0\\\\nr12     0x101010101010101\\\\nr13     0xffffa42a96b0\\\\nr14     0x2\\\\nr15     0x20\\\\nr16     0x0\\\\nr17     0x3\\\\nr18     0x2310000\\\\nr19     0x23a5000\\\\nr20     0xffffa42aa090\\\\nr21     0x23a5a50\\\\nr22     0xffffa42a95a8\\\\nr23     0xffff9c0008c0\\\\nr24     0x131fae0\\\\nr25     0xd2166f0\\\\nr26     0x18aa1a8\\\\nr27     0x22eb030\\\\nr28     0x4420000ea0\\\\nr29     0xffffa42a9270\\\\nlr      0x13481d0\\\\nsp      0xffffa42a9270\\\\npc      0x1347ec8\\\\nfault   0x8\\\\n\\\"\""
[0moci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 0 caused \\\"error running hook: exit status 2, stdout: , stderr: runtime/cgo: pthread_create failed: Resource temporarily unavailable\\\\nSIGABRT: abort\\\\nPC=0x1347ec8 m=3 sigcode=18446744073709551610\\\\n\\\\ngoroutine 0 [idle]:\\\\n\\\\ngoroutine 1 [IO wait]:\\\\nnet.runtime_pollWait(0xffffa2a7bf70, 0x72, 0x5)\\\\n\\\\t/usr/src/go/src/runtime/netpoll.go:164 +0x3c\\\\nnet.(*pollDesc).wait(0x442043ce68, 0x72, 0xffffffffffffffff, 0x231f880)\\\\n\\\\t/usr/src/go/src/net/fd_poll_runtime.go:75 +0x2c\\\\nnet.(*pollDesc).waitRead(0x442043ce68, 0x4420415400, 0x400)\\\\n\\\\t/usr/src/go/src/net/fd_poll_runtime.go:80 +0x28\\\\nnet.(*netFD).Read(0x442043ce00, 0x4420415400, 0x400, 0x400, 0x0, 0x231f880, 0x2311978)\\\\n\\\\t/usr/src/go/src/net/fd_unix.go:250 +0x148\\\\nnet.(*conn).Read(0x442000e790, 0x4420415400, 0x400, 0x400, 0x0, 0x0, 0x0)\\\\n\\\\t/usr/src/go/src/net/net.go:181 +0x50\\\\ngithub.com/docker/docker/vendor/github.com/docker/libnetwork.processReturn(0xffffa2a7c228, 0x442000e790, 0x442000e790, 0xffffa2a7c228)\\\\n\\\\t/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox_externalkey_unix.go:94 +0x64\\\\ngithub.com/docker/docker/vendor/github.com/docker/libnetwork.SetExternalKey(0xfffff7907f27, 0x40, 0xfffff7907ee6, 0x40, 0x442042eee0, 0x12, 0x0, 0x0)\\\\n\\\\t/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox_externalkey_unix.go:72 +0x1a4\\\\ngithub.com/docker/docker/vendor/github.com/docker/libnetwork.processSetKeyReexec()\\\\n\\\\t/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/sandbox_externalkey_unix.go:54 +0x1dc\\\\ngithub.com/docker/docker/pkg/reexec.Init(0x0)\\\\n\\\\t/go/src/github.com/docker/docker/pkg/reexec/reexec.go:26 +0x7c\\\\nmain.main()\\\\n\\\\t/go/src/github.com/docker/docker/cmd/dockerd/docker.go:88 +0x18\\\\n\\\\ngoroutine 17 [syscall, locked to thread]:\\\\nruntime.goexit()\\\\n\\\\t/usr/src/go/src/runtime/asm_arm64.s:981 +0x4\\\\n\\\\ngoroutine 6 [syscall]:\\\\nos/signal.signal_recv(0x0)\\\\n\\\\t/usr/src/go/src/runtime/sigqueue.go:116 +0xd8\\\\nos/signal.loop()\\\\n\\\\t/usr/src/go/src/os/signal/signal_unix.go:22 +0x18\\\\ncreated by os/signal.init.1\\\\n\\\\t/usr/src/go/src/os/signal/signal_unix.go:28 +0x30\\\\n\\\\nr0      0x0\\\\nr1      0x4fe0\\\\nr2      0x6\\\\nr3      0xffffa42aa090\\\\nr4      0x4fd5\\\\nr5      0xffffa42aa780\\\\nr6      0x0\\\\nr7      0x0\\\\nr8      0x83\\\\nr9      0xffffff80ffffffc8\\\\nr10     0x73\\\\nr11     0xffffa42a6bb0\\\\nr12     0x101010101010101\\\\nr13     0xffffa42a96b0\\\\nr14     0x2\\\\nr15     0x20\\\\nr16     0x0\\\\nr17     0x3\\\\nr18     0x2310000\\\\nr19     0x23a5000\\\\nr20     0xffffa42aa090\\\\nr21     0x23a5a50\\\\nr22     0xffffa42a95a8\\\\nr23     0xffff9c0008c0\\\\nr24     0x131fae0\\\\nr25     0xd2166f0\\\\nr26     0x18aa1a8\\\\nr27     0x22eb030\\\\nr28     0x4420000ea0\\\\nr29     0xffffa42a9270\\\\nlr      0x13481d0\\\\nsp      0xffffa42a9270\\\\npc      0x1347ec8\\\\nfault   0x8\\\\n\\\"\""

exit status 1
df7aa73bcb5a5934f8ea5b7b67ca6dce62a85d0a: Pulling from zededa/ztools
no matching manifest for linux/arm64 in the manifest list entries
Error response from daemon: No such image: zededa/ztools:df7aa73bcb5a5934f8ea5b7b67ca6dce62a85d0a
The push refers to a repository [docker.io/zededa/ztools]
tag does not exist: zededa/ztools:latest-arm64
make: Entering directory '/home/zededa-ci/src/zenbuild/pkg'
(cd ..; ./parse-pkgs.sh pkg/kmod_pfring/Dockerfile.in > pkg/kmod_pfring/Dockerfile)
(cd ..; ./parse-pkgs.sh pkg/qrexec-lib/Dockerfile.in > pkg/qrexec-lib/Dockerfile)
(cd ..; ./parse-pkgs.sh pkg/qrexec-dom0/Dockerfile.in > pkg/qrexec-dom0/Dockerfile)
(cd ..; ./parse-pkgs.sh pkg/zedctr/Dockerfile.in > pkg/zedctr/Dockerfile)
(cd ..; ./parse-pkgs.sh pkg/mkconf/Dockerfile.in > pkg/mkconf/Dockerfile)
(cd ..; ./parse-pkgs.sh pkg/mkflash/Dockerfile.in > pkg/mkflash/Dockerfile)
(cd ..; ./parse-pkgs.sh pkg/mkimage-iso-efi/Dockerfile.in > pkg/mkimage-iso-efi/Dockerfile)
(cd ..; ./parse-pkgs.sh pkg/mkimage-raw-efi//Dockerfile.in > pkg/mkimage-raw-efi//Dockerfile)
Building and pushing "zededa/grub:8e9e055548f7b965cf6ffd7a0ac3ebab679a01e1"
8e9e055548f7b965cf6ffd7a0ac3ebab679a01e1: Pulling from zededa/grub
no matching manifest for linux/arm64 in the manifest list entries
No image pulled, continuing with build
Sending build context to Docker daemon  13.31kB
Step 1/16 : FROM linuxkit/alpine:8b53d842a47fce43464e15f65ee2f68b82542330 AS grub-build
 ---> 3845c352aaeb
Step 2/16 : RUN apk add   automake   make   bison   gettext   flex   gcc   git   libtool   libc-dev   linux-headers   python3   autoconf
 ---> Using cache
 ---> aaab2efeb900
Step 3/16 : RUN ln -s python3 /usr/bin/python
 ---> Using cache
 ---> 238299280053
Step 4/16 : ENV GRUB_MODULES_PORT "part_gpt fat ext2 iso9660 squash4 gzio linux acpi normal cpio crypto disk boot crc64 gpt search_disk_uuid verify xzio xfs video gfxterm efi_gop gptprio chain probe reboot regexp getenv part_msdos"
 ---> Using cache
 ---> d22f2f3ade38
Step 5/16 : ENV GRUB_MODULES_x86_64 "multiboot2 efi_uga linuxefi"
 ---> Using cache
 ---> d07ad0d4ce1b
Step 6/16 : ENV GRUB_MODULES_aarch64 "xen_boot"
 ---> Using cache
 ---> 0cf2b1b42723
Step 7/16 : ENV GRUB_COMMIT 6782f6d431d22b4e9ab14e94d263795c7991e160
 ---> Using cache
 ---> 3f2ffc85c403
Step 8/16 : COPY patches/* /patches/
 ---> Using cache
 ---> 4a8a5610ed7f
Step 9/16 : RUN mkdir /grub-lib &&   set -e &&   git clone https://github.com/coreos/grub.git &&   cd grub &&   git checkout -b grub-build ${GRUB_COMMIT} &&   for patch in /patches/*.patch; do     echo "Applying $patch";     patch -p1 < "$patch";   done &&   ./autogen.sh &&   ./configure --libdir=/grub-lib --with-platform=efi CFLAGS="-Os -Wno-unused-value" &&   make -j "$(getconf _NPROCESSORS_ONLN)" &&   make install
 ---> Running in 4b8cf17d3451
[91mcontainer_linux.go:265: starting container process caused "process_linux.go:264: starting init process command caused \"fork/exec /proc/self/exe: resource temporarily unavailable\""
[0moci runtime error: container_linux.go:265: starting container process caused "process_linux.go:264: starting init process command caused \"fork/exec /proc/self/exe: resource temporarily unavailable\""

exit status 1
Makefile:16: recipe for target 'push' failed
make: *** [push] Error 1
make: Leaving directory '/home/zededa-ci/src/zenbuild/pkg'
make: Entering directory '/home/zededa-ci/src/zenbuild/build-pkgs'
Building and pushing "zededa/build-pkgs_abuild:7ae4d9f9fa290963de466d5ed96d6c9318354824"
7ae4d9f9fa290963de466d5ed96d6c9318354824: Pulling from zededa/build-pkgs_abuild
Digest: sha256:ba07e9431235007b6a2efc3f9d1f8b57afcad774956748e48770af84c7a06fd3
Status: Image is up to date for zededa/build-pkgs_abuild:7ae4d9f9fa290963de466d5ed96d6c9318354824
Building and pushing "zededa/build-pkgs_uefi:a3362428c518fb4db1a136a961bd17e8a66fb693"
a3362428c518fb4db1a136a961bd17e8a66fb693: Pulling from zededa/build-pkgs_uefi
Digest: sha256:adbf043c596d4c5fed11fe2ff39e5b0cd08da973a9de99979a8a675cfa91a067
Status: Image is up to date for zededa/build-pkgs_uefi:a3362428c518fb4db1a136a961bd17e8a66fb693
make: Leaving directory '/home/zededa-ci/src/zenbuild/build-pkgs'
tee: /dev/tty: No such device or address
Error response from daemon: manifest for zededa/zedctr:1d2d5bbee2379fab87dbeddad3cdfe0c1717187e-arm64 not found
./parse-pkgs.sh images/installer.yml.in > images/installer.yml
./parse-pkgs.sh images/fallback.yml.in > images/fallback.yml
./makerootfs.sh images/fallback.yml squash rootfs_aarch64.img
Extract kernel image: zededa/kernel:2f3f0ca93049e132867b9f9a836848e6ecc03f4b-arm64
Unable to find image 'zededa/mkrootfs-squash:1133d9607d141ecf099aa3cd397a5df7dfc33d87' locally
1133d9607d141ecf099aa3cd397a5df7dfc33d87: Pulling from zededa/mkrootfs-squash
docker: no matching manifest for linux/arm64 in the manifest list entries.
See 'docker run --help'.
Makefile:114: recipe for target 'rootfs_aarch64.img' failed
make: *** [rootfs_aarch64.img] Error 125
The push refers to a repository [docker.io/zededa/zenix]
tag does not exist: zededa/zenix:latest-arm64
